// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Security.Domain.Entities
{
    public partial class Employee
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string Office { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string Division { get; set; }
        public string Position { get; set; }
        public int Grade { get; set; }
        public DateTime BeginDate { get; set; }
        public DateTime Birthday { get; set; }
        public string IdentificationNumber { get; set; }
        public decimal BaseSalary { get; set; }
        public decimal ProductionBonus { get; set; }
        public decimal CompesationBonus { get; set; }
        public decimal Comission { get; set; }
        public decimal Constributions { get; set; }
    }
}