// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Security.Domain.Entities;

namespace Security.Infrastructure.DataModel.Context.Configurations
{
    public partial class MenuActionConfiguration : IEntityTypeConfiguration<MenuAction>
    {
        public void Configure(EntityTypeBuilder<MenuAction> entity)
        {
            entity.ToTable("MenuAction");

            entity.Property(e => e.DateCrea).HasColumnType("datetime");

            entity.Property(e => e.DateUpd).HasColumnType("datetime");

            entity.HasOne(d => d.Action)
                .WithMany(p => p.MenuActions)
                .HasForeignKey(d => d.IdAction)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MenuAction_Action");

            entity.HasOne(d => d.Menu)
                .WithMany(p => p.MenuActions)
                .HasForeignKey(d => d.IdMenu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MenuAction_Menu1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MenuAction> entity);
    }
}
